### ISSUE TITLE
Från homepage använd bottomnavigation och tillbaka till "hem" igen. Då funkar inte homepage navigation

### ISSUE THREAD

**Issue by FThelin** [FThelin/mitt-lag---frontend#24]
Endast på web.
LÖST

**Comment by simonbeijer** [comment]
Views från manage team ligger kvar över home page. Funkar på mobilen. Kan vara nått med TouchableOpacity med positioner. 
[https://stackoverflow.com/questions/39250449/react-native-touchableopacity-not-working-inside-an-absolute-positioned-view](url)
